import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { initialState } from "../src/lib/model.ts";
import { applyAction, checkAiPermission } from "../src/lib/action-core.ts";
import { executeAction, decideProposal } from "@/lib/actions";
import { readState, updateState } from "@/lib/store";
import { readSecret, saveSecret } from "@/lib/secrets";
import { runAi } from "@/lib/ai";
import { LocalStorageProvider } from "@/lib/storage";
import { selectedImageInputs } from "@/lib/ai-media";
import { uploadMedia } from "@/lib/media";

test("one action layer handles tasks, content, schedules, ideas and media links", () => {
  const state = initialState(); const projectId = state.activeProjectId;
  const task = applyAction(state, { name: "createTask", args: { projectId, title: "Marker setzen" } });
  applyAction(state, { name: "updateTask", args: { id: task.id, status: "doing", dueAt: "2026-10-08T17:00:00Z" } });
  applyAction(state, { name: "completeTask", args: { id: task.id } });
  assert.equal(state.tasks[0].status, "done");
  applyAction(state, { name: "updateContent", args: { id: projectId, caption: "Comeback", hooks: ["Anfang des Jahres"] } });
  applyAction(state, { name: "scheduleContent", args: { id: projectId, publishAt: "2026-10-09T16:00:00Z", platform: "YouTube" } });
  assert.equal(state.projects[0].platform, "YouTube");
  applyAction(state, { name: "createIdea", args: { id: "stable", text: "Hook", projectId } });
  applyAction(state, { name: "createIdea", args: { id: "stable", text: "Hook", projectId } });
  assert.equal(state.ideas.filter((idea) => idea.id === "stable").length, 1);
  state.media.push({ id: "media", links: [] });
  applyAction(state, { name: "attachMedia", args: { mediaId: "media", entityType: "task", entityId: task.id, role: "reference" } });
  applyAction(state, { name: "attachMedia", args: { mediaId: "media", entityType: "task", entityId: task.id, role: "raw" } });
  assert.equal(state.media[0].links.length, 1);
  applyAction(state, { name: "detachMedia", args: { mediaId: "media", entityType: "task", entityId: task.id } });
  assert.equal(state.media[0].links.length, 0);
  const other = applyAction(state, { name: "createContent", args: { title: "Other" } });
  applyAction(state, { name: "updateTask", args: { id: task.id, projectId: other.id } });
  assert.equal(state.tasks[0].projectId, other.id);
  const plan = applyAction(state, { name: "createPlanning", args: { title: "Schnitt", startsAt: "2026-10-09T12:00:00Z", projectId } });
  applyAction(state, { name: "updatePlanning", args: { id: plan.id, startsAt: "2026-10-10T12:00:00Z" } });
  assert.equal(state.planning[0].startsAt, "2026-10-10T12:00:00.000Z");
  assert.throws(() => applyAction(state, { name: "createTask", args: { projectId: "missing", title: "No" } }), /nicht gefunden/);
});

test("AI permissions cannot be bypassed through a different action name", () => {
  const state = initialState(); state.integrations.ai.enabled = true;
  assert.throws(() => checkAiPermission(state, { name: "createTask", args: {} }), /nicht freigegeben/);
  state.integrations.ai.permissions = ["task.update", "content.update"];
  assert.throws(() => checkAiPermission(state, { name: "updateTask", args: { status: "done" } }), /nicht freigegeben/);
  assert.throws(() => checkAiPermission(state, { name: "updateContent", args: { publishAt: "2026-10-09T12:00:00Z" } }), /nicht freigegeben/);
  assert.throws(() => applyAction(state, { name: "completeTask", args: { id: "task", title: "Edited" } }), /ändert nur/);
});

test("AI proposals, automatic mode, confirmation, conflicts, encrypted credentials and tool loop", async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "creatoros-actions-"));
  const previous = process.env.CREATOROS_DATA_DIR; process.env.CREATOROS_DATA_DIR = directory;
  const originalFetch = globalThis.fetch;
  try {
    const state = await readState(); const projectId = state.activeProjectId;
    const secretId = await saveSecret({ apiKey: "test-credential-only" });
    assert.equal((await readSecret(secretId)).apiKey, "test-credential-only");
    assert.ok(!(await readFile(path.join(directory, "integrations.vault.json"), "utf8")).includes("test-credential-only"));
    await updateState((current) => { current.integrations.ai = { ...current.integrations.ai, enabled: true, secretId, permissions: ["task.create","task.update","task.complete","content.create","content.update","content.schedule"], mode: "suggest" }; });
    const proposed = await executeAction({ name: "createTask", args: { projectId, title: "Proposed" } }, "ai");
    assert.equal(proposed.result.outcome, "proposal"); assert.equal(proposed.state.tasks.length, 0);
    const approved = await decideProposal(proposed.result.proposal.id, true);
    assert.equal(approved.state.tasks.length, 1);
    await assert.rejects(() => decideProposal(proposed.result.proposal.id, true), /nicht mehr verfügbar/);
    const taskId = approved.state.tasks[0].id;
    const update = await executeAction({ name: "updateTask", args: { id: taskId, title: "New" } }, "ai");
    await executeAction({ name: "updateTask", args: { id: taskId, title: "Manual change" } });
    await assert.rejects(() => decideProposal(update.result.proposal.id, true), /inzwischen geändert/);
    const revoked = await executeAction({ name: "completeTask", args: { id: taskId } }, "ai");
    await updateState((current) => { current.integrations.ai.permissions = ["task.create","content.create","content.schedule"]; current.integrations.ai.mode = "auto"; });
    await assert.rejects(() => decideProposal(revoked.result.proposal.id, true), /nicht freigegeben/);
    const automatic = await executeAction({ name: "createContent", args: { title: "AI content" } }, "ai");
    assert.equal(automatic.result.outcome, "applied");
    const critical = await executeAction({ name: "scheduleContent", args: { id: projectId, publishAt: "2026-10-10T10:00:00Z" } }, "ai");
    assert.equal(critical.result.outcome, "proposal");
    assert.equal(critical.state.projects.find((item) => item.id === projectId).publishAt, undefined);
    const upload = { name: "uploadMedia", args: { entityType: "project", entityId: projectId, filename: "Skript-Entwurf.txt", content: "  Hook und Einstieg\n", role: "reference" } };
    await assert.rejects(() => executeAction(upload, "ai"), /nicht freigegeben/);
    await updateState((current) => { current.integrations.ai.permissions.push("media.upload"); });
    await assert.rejects(() => executeAction(upload, "ai"), /nicht freigegeben/);
    await updateState((current) => { current.integrations.ai.permissions.push("media.attach"); current.integrations.ai.requireConfirmation = ["content.schedule","media.attach"]; });
    const fileProposal = await executeAction(upload, "ai");
    assert.equal(fileProposal.result.outcome, "proposal");
    assert.equal(fileProposal.state.media.length, 0);
    const savedFile = await decideProposal(fileProposal.result.proposal.id, true);
    assert.equal(savedFile.state.media.length, 1);
    assert.equal(savedFile.state.actionProposals.find((item) => item.id === fileProposal.result.proposal.id).status, "applied");
    const media = savedFile.state.media[0];
    assert.equal(media.links[0].role, "reference");
    assert.equal(await new Response((await new LocalStorageProvider().getFile(media.relativePath)).body).text(), upload.args.content);
    await assert.rejects(() => decideProposal(fileProposal.result.proposal.id, true), /nicht mehr verfügbar/);
    await assert.rejects(() => executeAction({ ...upload, args: { ...upload.args, filename: "../escape.txt" } }, "ai"), /TXT-/);
    await assert.rejects(() => executeAction({ ...upload, args: { ...upload.args, filename: "invalid.json" } }, "ai"), /gültiges JSON/);
    const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aDRkAAAAASUVORK5CYII=", "base64");
    const picture = await uploadMedia(new Request("http://creatoros/api/media?" + new URLSearchParams({ entityId: projectId, role: "reference" }), { method: "POST", headers: { "x-file-name": "Moodboard.png", "x-file-size": String(png.length) }, body: png }));
    assert.deepEqual(await selectedImageInputs(picture.state, [], projectId), [], "No implicit image transmission");
    const imageInput = await selectedImageInputs(picture.state, [picture.media.id], projectId);
    assert.equal(imageInput[1].type, "input_image"); assert.match(imageInput[1].image_url, /^data:image\/png;base64,/);
    await assert.rejects(() => selectedImageInputs(picture.state, [picture.media.id], "another-project"), /gehört nicht/);
    await assert.rejects(() => selectedImageInputs(picture.state, [picture.media.id,picture.media.id], projectId), /unterschiedliche/);
    let round = 0;
    globalThis.fetch = async (url, options) => {
      assert.equal(url, "https://api.openai.com/v1/responses");
      const body = JSON.parse(options.body); assert.equal(body.store, false);
      assert.deepEqual(body.include, ["reasoning.encrypted_content"]);
      assert.ok(body.input[0].content.some((item) => item.type === "input_image"));
      if (round++ === 0) return Response.json({ output: [{ type: "function_call", name: "createTask", call_id: "call", arguments: JSON.stringify({ projectId, title: "From tool" }) }] });
      assert.ok(body.input.some((item) => item.type === "function_call_output"));
      return Response.json({ output: [{ type: "message", content: [{ type: "output_text", text: "Aufgabe angelegt." }] }] });
    };
    const aiResult = await runAi("Lege eine Aufgabe an", projectId, [picture.media.id]);
    assert.equal(aiResult.answer, "Aufgabe angelegt.");
    assert.ok(aiResult.state.tasks.some((item) => item.title === "From tool"));
    assert.equal(round, 2);
    let failedRound = 0;
    globalThis.fetch = async () => {
      if (failedRound++ === 0) return Response.json({ output: [{ type: "function_call", name: "createTask", call_id: "partial", arguments: JSON.stringify({ projectId, title: "Saved before interruption" }) }] });
      throw new Error("Fixture provider interrupted");
    };
    const partial = await runAi("Erstelle eine Aufgabe", projectId);
    assert.match(partial.warning, /erneut versuchen/);
    assert.ok(partial.state.tasks.some((item) => item.title === "Saved before interruption"));
    assert.match(partial.answer, /Bereits gespeicherte/);
  } finally {
    globalThis.fetch = originalFetch;
    if (previous === undefined) delete process.env.CREATOROS_DATA_DIR; else process.env.CREATOROS_DATA_DIR = previous;
    if (path.dirname(directory) !== os.tmpdir()) throw new Error("Unexpected temporary directory");
    await rm(directory, { recursive: true, force: true });
  }
});
