"use client";
import { useEffect, useRef, useState } from "react";
import { Check, Send, Sparkles, X } from "lucide-react";
import type { CreatorState } from "@/lib/model";
import { appRequest } from "@/lib/client-api";
export default function AiPanel({ data, projectId, onState }: { data: CreatorState; projectId: string | null; onState: (state: CreatorState) => void }) {
  const [question,setQuestion] = useState(""); const [messages,setMessages] = useState<{ role: "user" | "assistant"; text: string; project: string }[]>([]); const [error,setError] = useState(""); const [busy,setBusy] = useState(false); const [imageIds,setImageIds] = useState<string[]>([]); const end = useRef<HTMLDivElement>(null);
  const images = data.media.filter((media) => ["image/png","image/jpeg","image/webp","image/gif"].includes(media.mimeType) && media.fileSize <= 6*1024*1024 && (!projectId || media.links.some((link) => link.entityType === "project" ? link.entityId === projectId : data.tasks.some((task) => task.id === link.entityId && task.projectId === projectId))));
  const proposals = data.actionProposals.filter((proposal) => proposal.status === "pending" && Date.parse(proposal.expiresAt) > Date.now());
  useEffect(() => { end.current?.scrollIntoView({ block: "nearest" }); },[messages.length,busy]);
  const decide = async (proposalId: string,approve: boolean) => { setBusy(true); setError(""); try { const result = await appRequest("/api/actions",{ proposalId,approve }); onState(result.state); } catch (cause) { setError(cause instanceof Error ? cause.message : "Vorschlag konnte nicht übernommen werden."); } finally { setBusy(false); } };
  return <section className="ai-panel assistant-chat"><div className="chat-messages" role="log" aria-label="Chat-Verlauf">{!messages.length && <div className="chat-welcome"><Sparkles size={28}/><h3>Ein kleiner nächster Schritt?</h3><p>Ich nutze dein Brain und den ausgewählten Projektkontext. Sag mir, wobei ich helfen soll.</p></div>}{messages.map((message,index) => <article className={"chat-message chat-"+message.role} key={index}><small>{message.role === "user" ? "Du" : "CreatorOS"} · {message.project}</small><p>{message.text}</p></article>)}{busy && <p className="chat-thinking" role="status">CreatorOS arbeitet …</p>}{error && <p className="brain-error" role="alert">{error}</p>}{proposals.length > 0 && <div className="ai-proposals"><h3>Änderungen prüfen</h3>{proposals.map((proposal) => <article className="ai-proposal" key={proposal.id}><b>{proposal.action.name}</b><pre>{JSON.stringify(proposal.action.args,null,2)}</pre><div className="screen-action-group"><button className="button-primary" disabled={busy} onClick={() => void decide(proposal.id,true)}><Check size={17}/> Übernehmen</button><button className="button-ghost" disabled={busy} onClick={() => void decide(proposal.id,false)}><X size={17}/> Verwerfen</button></div></article>)}</div>}<div ref={end}/></div>
  <form className="chat-composer" onSubmit={async (event) => {
    event.preventDefault(); if (!question.trim() || busy) return; const text = question.trim(); const project = data.projects.find((item) => item.id === projectId)?.title || "Workspace";
    setBusy(true); setError(""); setQuestion(""); const history = messages.slice(-12).map(({ role,text }) => ({ role,text: text.slice(0,4000) })); setMessages((current) => [...current,{ role: "user",text,project }]);
    try { const result = await appRequest("/api/ai/chat",{ question: text,projectId,imageIds: imageIds.filter((id) => images.some((image) => image.id === id)),history },6*60*1000); onState(result.state); setMessages((current) => [...current,{ role: "assistant",text: result.answer,project }]); setImageIds([]); if (result.warning) setError(result.warning); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "AI-Anfrage fehlgeschlagen."); setQuestion(text); setMessages((current) => current.slice(0,-1)); } finally { setBusy(false); }
  }}>{images.length > 0 && <details className="chat-references"><summary>Bildreferenzen ({imageIds.length}/3)</summary><small>Nur ausgewählte Bilder werden übertragen.</small>{images.map((image) => <label key={image.id}><input type="checkbox" checked={imageIds.includes(image.id)} disabled={busy || (!imageIds.includes(image.id) && imageIds.length >= 3)} onChange={(event) => setImageIds(event.target.checked ? [...imageIds,image.id] : imageIds.filter((id) => id !== image.id))}/>{image.displayName}</label>)}</details>}<div className="chat-input-row"><textarea aria-label="Nachricht an CreatorOS" rows={3} value={question} maxLength={4000} required disabled={busy} onChange={(event) => setQuestion(event.target.value)} placeholder="Was machen wir als Nächstes?" onKeyDown={(event) => { if (event.key === "Enter" && (event.ctrlKey || event.metaKey)) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }}/><button className="button-primary chat-send" aria-label="Nachricht senden" disabled={busy || !question.trim()}><Send size={21}/></button></div><div className="chat-composer-footer"><small>{data.integrations.ai.provider === "codex" ? "Codex-Abonnement" : "OpenAI API"} · {data.integrations.ai.mode === "auto" ? "Freigegebene Aktionen" : "Änderungen mit Bestätigung"}</small><button type="button" className="text-action" disabled={busy || !messages.length} onClick={() => { setMessages([]); setError(""); setImageIds([]); }}>Neuer Chat</button></div></form></section>;
}
