"use client";
import { useEffect, useRef, useState } from "react";
import { appRequest } from "@/lib/client-api";
import type { CreatorState } from "@/lib/model";
type Auth = { connected: boolean; account?: { email: string; planType: string }; message: string; login?: { type: string; authUrl?: string; verificationUrl?: string; userCode?: string; expiresAt: number } };
export default function CodexLogin({ onState }: { onState: (state: CreatorState) => void }) {
  const [auth, setAuth] = useState<Auth | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const callback = useRef<HTMLInputElement>(null);
  useEffect(() => { let live = true; void fetch("/api/codex/auth", { cache: "no-store" }).then(async (response) => { const value = await response.json(); if (!response.ok) throw new Error(value.error); if (live) setAuth(value); }).catch((cause) => { if (live) setError(cause.message); }); return () => { live = false; }; }, []);
  useEffect(() => {
    if (!auth?.login) return;
    let live = true;
    const interval = setInterval(() => { void fetch("/api/codex/auth", { cache: "no-store", signal: AbortSignal.timeout(10000) }).then(async (response) => { const value = await response.json(); if (!response.ok) throw new Error(value.error); if (!live) return; setAuth(value); if (!value.login) { onState(value.state); setError(""); } }).catch((cause) => { if (live) setError(cause.message); }); }, 4000);
    return () => { live = false; clearInterval(interval); };
  }, [Boolean(auth?.login), onState]);
  const act = async (operation: string, type?: string) => { setBusy(true); setError(""); try { const value = await appRequest("/api/codex/auth", { operation, type, ...(operation === "completeBrowser" ? { callback: callback.current?.value || "" } : {}) }, 75000); setAuth(value); onState(value.state); if (callback.current) callback.current.value = ""; } catch (cause) { setError(cause instanceof Error ? cause.message : "Anmeldung fehlgeschlagen."); } finally { setBusy(false); } };
  return <div className="codex-login"><h3>Mit ChatGPT / Codex anmelden</h3><p>Verwendet dein Codex-Abonnement und dessen Nutzungslimits. CreatorOS besitzt eine eigene Anmeldung auf dem App-Host.</p>{auth?.connected ? <><p className="integration-status connected">Verbunden · {auth.account?.email} · {auth.account?.planType}</p><button className="button-ghost" disabled={busy} onClick={() => void act("logout")}>Codex abmelden</button></> : !auth?.login ? <div className="screen-action-group"><button className="button-primary" disabled={busy} onClick={() => void act("login","chatgptDeviceCode")}>Mit Device-Code anmelden</button><button className="button-secondary" disabled={busy} onClick={() => void act("login","chatgpt")}>Im Browser anmelden</button></div> : <div className="codex-login-pending">{auth.login.userCode && <><span>Einmalcode</span><strong className="device-code">{auth.login.userCode}</strong><small>Für Home Assistant empfohlen. Device-Code-Anmeldung muss in den ChatGPT-Sicherheitseinstellungen erlaubt sein.</small></>}<a className="button-primary" target="_blank" rel="noopener noreferrer" href={auth.login.authUrl || auth.login.verificationUrl}>Anmeldeseite öffnen</a>{auth.login.type === "chatgpt" && <form className="integration-form" onSubmit={(event) => { event.preventDefault(); void act("completeBrowser"); }}><small>Falls der Browser nach der Anmeldung localhost nicht erreicht: die vollständige Rücksprungadresse aus der Adressleiste hier einfügen. CreatorOS übernimmt sie auf dem Home-Assistant-Host.</small><label>Rücksprungadresse<input ref={callback} type="password" autoComplete="off" required maxLength={12000} placeholder="http://localhost:…/auth/callback?…"/></label><button className="button-secondary" disabled={busy}>Anmeldung abschließen</button></form>}<button className="button-ghost" disabled={busy} onClick={() => void act("cancel")}>Anmeldung abbrechen</button></div>}{auth?.message && <small role="status">{auth.message}</small>}{error && <p className="brain-error" role="alert">{error}</p>}</div>;
}
