"use client";
import { useEffect, useRef, useState } from "react";
import { Check, Mic, MicOff, RotateCcw, Send, Sparkles, X } from "lucide-react";
import type { CreatorState } from "@/lib/model";
import { appRequest } from "@/lib/client-api";
import { summarizeAiAction } from "@/lib/ai-action-summary";
type SpeechRecognitionLike = {
  lang: string; interimResults: boolean;
  onresult: ((event: { results: ArrayLike<ArrayLike<{ transcript: string }>> }) => void) | null;
  onerror: (() => void) | null; onend: (() => void) | null; start: () => void; stop: () => void;
};
export default function AiPanel({ data, projectId, onState }: { data: CreatorState; projectId: string | null; onState: (state: CreatorState) => void }) {
  const [question,setQuestion] = useState(""); const [messages,setMessages] = useState<{ role: "user" | "assistant"; text: string; project: string; actions?: { title: string; details: string[] }[] }[]>([]); const [error,setError] = useState(""); const [voiceHelp,setVoiceHelp] = useState(""); const [listening,setListening] = useState(false); const [busy,setBusy] = useState(false); const [imageIds,setImageIds] = useState<string[]>([]); const end = useRef<HTMLDivElement>(null); const input = useRef<HTMLTextAreaElement>(null); const recognition = useRef<SpeechRecognitionLike | null>(null);
  const images = data.media.filter((media) => ["image/png","image/jpeg","image/webp","image/gif"].includes(media.mimeType) && media.fileSize <= 6*1024*1024 && (!projectId || media.links.some((link) => link.entityType === "project" ? link.entityId === projectId : data.tasks.some((task) => task.id === link.entityId && task.projectId === projectId))));
  const proposals = data.actionProposals.filter((proposal) => proposal.status === "pending" && Date.parse(proposal.expiresAt) > Date.now());
  useEffect(() => { end.current?.scrollIntoView({ block: "nearest" }); },[messages.length,busy]);
  useEffect(() => () => recognition.current?.stop(),[]);
  const speak = () => {
    setVoiceHelp("");
    if (listening) { recognition.current?.stop(); setListening(false); return; }
    const browser = window as unknown as { SpeechRecognition?: new() => SpeechRecognitionLike; webkitSpeechRecognition?: new() => SpeechRecognitionLike };
    const SpeechRecognition = browser.SpeechRecognition || browser.webkitSpeechRecognition;
    if (!SpeechRecognition) { input.current?.focus(); setVoiceHelp("Spracheingabe nicht verfügbar. Nutze das Mikrofon deiner Handy-Tastatur."); return; }
    const instance = new SpeechRecognition(); instance.lang = "de-AT"; instance.interimResults = false;
    instance.onresult = (event) => { const phrase = Array.from(event.results).map((result) => result[0]?.transcript || "").join(" "); setQuestion((current) => `${current}${current ? " " : ""}${phrase}`); };
    instance.onerror = () => { setListening(false); setVoiceHelp("Mikrofon nicht verfügbar. Nutze das Mikrofon deiner Handy-Tastatur."); input.current?.focus(); };
    instance.onend = () => setListening(false); recognition.current = instance; setListening(true);
    try { instance.start(); } catch { setListening(false); setVoiceHelp("Mikrofon nicht verfügbar. Nutze das Mikrofon deiner Handy-Tastatur."); }
  };
  const decide = async (proposalId: string,approve: boolean) => { setBusy(true); setError(""); try { const result = await appRequest("/api/actions",{ proposalId,approve }); onState(result.state); } catch (cause) { setError(cause instanceof Error ? cause.message : "Vorschlag konnte nicht übernommen werden."); } finally { setBusy(false); } };
  return <section className="ai-panel assistant-chat"><div className="chat-messages" role="log" aria-label="Chat-Verlauf">{!messages.length && <div className="chat-welcome"><Sparkles size={28}/><h3>Ein kleiner nächster Schritt?</h3><p>Ich nutze dein Brain und den ausgewählten Projektkontext. Sag mir, wobei ich helfen soll.</p></div>}{messages.map((message,index) => <article className={"chat-message chat-"+message.role} key={index}><small>{message.role === "user" ? "Du" : "CreatorOS"} · {message.project}</small><p>{message.text}</p>{!!message.actions?.length && <div className="chat-action-summaries">{message.actions.map((action,actionIndex) => <section className="chat-action-summary" key={actionIndex}><b>{action.title}</b>{action.details.map((detail,detailIndex) => <span key={detailIndex}>{detail}</span>)}</section>)}</div>}</article>)}{busy && <p className="chat-thinking" role="status">CreatorOS arbeitet …</p>}{error && <p className="brain-error" role="alert">{error}</p>}{proposals.length > 0 && <div className="ai-proposals"><h3>Änderungen prüfen</h3>{proposals.map((proposal) => { const summary = summarizeAiAction(proposal.action,data); return <article className="ai-proposal" key={proposal.id}><b>{summary.title}</b>{summary.details.filter((detail) => detail !== "Wartet auf deine Bestätigung").map((detail,index) => <span className="ai-proposal-detail" key={index}>{detail}</span>)}<div className="screen-action-group"><button className="button-primary" disabled={busy} onClick={() => void decide(proposal.id,true)}><Check size={17}/> Übernehmen</button><button className="button-ghost" disabled={busy} onClick={() => void decide(proposal.id,false)}><X size={17}/> Verwerfen</button></div></article>;})}</div>}<div ref={end}/></div>
  <form className="chat-composer" onSubmit={async (event) => {
    event.preventDefault(); if (!question.trim() || busy) return; const text = question.trim(); const project = data.projects.find((item) => item.id === projectId)?.title || "Workspace";
    setBusy(true); setError(""); setQuestion(""); const history = messages.slice(-12).map(({ role,text }) => ({ role,text: text.slice(0,4000) })); setMessages((current) => [...current,{ role: "user",text,project }]);
    try { const result = await appRequest("/api/ai/chat",{ question: text,projectId,imageIds: imageIds.filter((id) => images.some((image) => image.id === id)),history },6*60*1000); onState(result.state); setMessages((current) => [...current,{ role: "assistant",text: result.answer,project,actions: result.actionSummaries }]); setImageIds([]); if (result.warning) setError(result.warning); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "AI-Anfrage fehlgeschlagen."); setQuestion(text); setMessages((current) => current.slice(0,-1)); } finally { setBusy(false); }
  }}>{images.length > 0 && <details className="chat-references"><summary>Bildreferenzen ({imageIds.length}/3)</summary><small>Nur ausgewählte Bilder werden übertragen.</small>{images.map((image) => <label key={image.id}><input type="checkbox" checked={imageIds.includes(image.id)} disabled={busy || (!imageIds.includes(image.id) && imageIds.length >= 3)} onChange={(event) => setImageIds(event.target.checked ? [...imageIds,image.id] : imageIds.filter((id) => id !== image.id))}/>{image.displayName}</label>)}</details>}{voiceHelp && <small className="chat-voice-help" role="status">{voiceHelp}</small>}<div className="chat-input-row"><textarea ref={input} aria-label="Nachricht an CreatorOS" rows={2} value={question} maxLength={4000} required disabled={busy} onChange={(event) => setQuestion(event.target.value)} placeholder="Nachricht schreiben …" onKeyDown={(event) => { if (event.key === "Enter" && (event.ctrlKey || event.metaKey)) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }}/><button type="button" className={`button-secondary chat-voice ${listening ? "is-listening" : ""}`} aria-label={listening ? "Diktat beenden" : "Spracheingabe"} title={listening ? "Diktat beenden" : "Spracheingabe"} disabled={busy} onClick={speak}>{listening ? <MicOff size={21}/> : <Mic size={21}/>}</button><button className="button-primary chat-send" aria-label="Nachricht senden" disabled={busy || !question.trim()}><Send size={21}/></button></div><div className="chat-composer-footer"><small>{data.integrations.ai.provider === "codex" ? "Codex-Abonnement" : "OpenAI API"} · {data.integrations.ai.mode === "auto" ? "Freigegebene Aktionen" : "Änderungen mit Bestätigung"}</small><button type="button" className="text-action" disabled={busy || !messages.length} onClick={() => { setMessages([]); setError(""); setImageIds([]); }}><RotateCcw className="chat-new-icon" size={16}/><span>Neuer Chat</span></button></div></form></section>;
}
