"use client";
import { useEffect, useState, type CSSProperties } from "react";
import { MessageCircle, Minus, Sparkles } from "lucide-react";
import type { CreatorState } from "@/lib/model";
import AiPanel from "@/components/ai-panel";
export default function AssistantWidget({ data, projectId, onState, onSetup }: { data: CreatorState; projectId: string | null; onState: (state: CreatorState) => void; onSetup: () => void }) {
  const [open,setOpen] = useState(false); const [context,setContext] = useState(projectId || ""); const [follow,setFollow] = useState(true);
  useEffect(() => { if (follow) setContext(projectId || ""); }, [projectId,follow]);
  const selected = data.projects.some((project) => project.id === context) ? context : "";
  const layout = data.assistantLayout; const pending = data.actionProposals.filter((item) => item.status === "pending" && Date.parse(item.expiresAt) > Date.now()).length;
  return <aside className={`assistant-widget position-${layout.position} ${open ? "is-open" : ""}`} style={{ "--chat-width": `${layout.width}px`,"--chat-height": `${layout.height}px` } as CSSProperties} aria-label="CreatorOS KI-Assistent">
    <div className="assistant-window" hidden={!open}><header className="assistant-window-header"><span className="assistant-avatar"><Sparkles size={22}/></span><div><b>CreatorOS Assistent</b><small>Direkt neben deiner Arbeit</small></div><button className="icon-quiet" aria-label="Chat einklappen" onClick={() => setOpen(false)}><Minus size={22}/></button></header>{data.integrations.ai.enabled ? <><div className="assistant-context"><label>Kontext<select aria-label="Chat-Projektkontext" value={selected} onChange={(event) => { setFollow(false); setContext(event.target.value); }}><option value="">Gesamter Workspace</option>{data.projects.map((project) => <option key={project.id} value={project.id}>{project.title}</option>)}</select></label><label className="assistant-follow"><input type="checkbox" checked={follow} onChange={(event) => setFollow(event.target.checked)}/> Aktuelles Projekt</label></div><AiPanel data={data} projectId={selected || null} onState={onState}/></> : <div className="chat-welcome"><Sparkles size={30}/><h3>Dein Assistent nebenbei</h3><p>Verbinde Codex mit deinem Abonnement oder richte einen API-Schlüssel ein.</p><button className="button-primary" onClick={() => { setOpen(false); onSetup(); }}>AI einrichten</button></div>}</div>
    <button className="assistant-badge" aria-label={open ? "KI-Chat einklappen" : "KI-Chat öffnen"} aria-expanded={open} onClick={() => setOpen(!open)}><MessageCircle size={24}/><span>AI Assistent</span>{pending > 0 && <b className="assistant-count">{pending}</b>}</button>
  </aside>;
}
export function AssistantSettings({ data,onState }: { data: CreatorState; onState: (state: CreatorState) => void }) {
  const [layout,setLayout] = useState(data.assistantLayout); const [busy,setBusy] = useState(false); const [message,setMessage] = useState("");
  return <article className="settings-card assistant-settings"><div className="settings-copy"><b>Schwebender KI-Chat</b><small>Position und Standardgröße. Auf dem Handy passt sich das Fenster an den verfügbaren Platz an.</small></div><form className="integration-form" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setMessage(""); try { const response = await fetch("/api/settings", { method: "PATCH",headers: { "Content-Type": "application/json" },body: JSON.stringify({ assistantLayout: layout }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); onState(result.state); setMessage("Chat-Ansicht gespeichert."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Speichern fehlgeschlagen."); } finally { setBusy(false); } }}><label>Position<select value={layout.position} onChange={(event) => setLayout({ ...layout,position: event.target.value as typeof layout.position })}><option value="bottom-right">Rechts unten</option><option value="bottom-left">Links unten</option><option value="top-right">Rechts oben</option><option value="top-left">Links oben</option></select></label><div className="integration-form-row"><label>Breite · {layout.width} px<input type="range" min={320} max={800} step={20} value={layout.width} onChange={(event) => setLayout({ ...layout,width: Number(event.target.value) })}/></label><label>Höhe · {layout.height} px<input type="range" min={360} max={900} step={20} value={layout.height} onChange={(event) => setLayout({ ...layout,height: Number(event.target.value) })}/></label></div><button className="button-secondary" disabled={busy}>Chat-Ansicht speichern</button>{message && <p role="status">{message}</p>}</form></article>;
}
