"use client";
import { useEffect, useRef, useState } from "react";
import { HardDrive, Link, Settings2, Sparkles, Unplug } from "lucide-react";
import type { AiPermission, CreatorState, IntegrationStatus } from "@/lib/model";
import { permissionLabels } from "@/lib/action-core";
import { appRequest } from "@/lib/client-api";
const labels: Record<IntegrationStatus, string> = { not_configured: "Nicht eingerichtet", connected: "Verbunden", error: "Verbindungsfehler", incomplete: "Konfiguration unvollständig" };

export default function IntegrationsScreen({ data, onState }: { data: CreatorState; onState: (state: CreatorState) => void }) {
  const [aiOpen, setAiOpen] = useState(false); const [nasOpen, setNasOpen] = useState(false);
  const [ai, setAi] = useState(data.integrations.ai); const [nas, setNas] = useState(data.integrations.nas);
  const [statuses, setStatuses] = useState({ ai: data.integrations.ai.status, nas: data.integrations.nas.status });
  const apiKey = useRef<HTMLInputElement>(null); const password = useRef<HTMLInputElement>(null);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [disconnect, setDisconnect] = useState<"ai" | "nas" | null>(null);
  useEffect(() => {
    let live = true;
    void fetch("/api/integrations", { cache: "no-store", signal: AbortSignal.timeout(5000) }).then((response) => response.json()).then((value) => { if (live && value.ai && value.nas) setStatuses({ ai: value.ai.status, nas: value.nas.status }); }).catch(() => {});
    return () => { live = false; };
  }, [data.updatedAt]);
  const run = async (kind: "ai" | "nas", operation: "save" | "test" | "disconnect", config?: unknown) => {
    setBusy(true); setMessage("");
    try {
      const result = await appRequest("/api/integrations", { kind, operation, config }, 30000);
      onState(result.state); setStatuses({ ai: result.state.integrations.ai.status, nas: result.state.integrations.nas.status });
      if (operation === "save") { if (apiKey.current) apiKey.current.value = ""; if (password.current) password.current.value = ""; setMessage("Gespeichert. Jetzt kannst du die Verbindung testen."); }
      if (operation === "test") setMessage(result.message);
      if (operation === "disconnect") { setDisconnect(null); setAiOpen(false); setNasOpen(false); setMessage("Verbindung getrennt."); }
    } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Integration konnte nicht geändert werden."); }
    finally { setBusy(false); }
  };
  const togglePermission = (permission: AiPermission, checked: boolean) => setAi((current) => ({ ...current, permissions: checked ? [...current.permissions, permission] : current.permissions.filter((item) => item !== permission) }));
  const toggleConfirmation = (permission: AiPermission, checked: boolean) => setAi((current) => ({ ...current, requireConfirmation: checked ? [...current.requireConfirmation, permission] : current.requireConfirmation.filter((item) => item !== permission) }));
  return <section><div className="screen-heading"><div><div className="eyebrow">OPTIONALE VERBINDUNGEN</div><h1>Integrationen</h1><p>AI spart Arbeit. NAS hält deine Dateien. Die manuellen Funktionen bleiben jederzeit verfügbar.</p></div></div>
    {message && <p className="integration-feedback" role="status">{message}</p>}
    <div className="integration-cards">
      <article className="integration-card"><div className="integration-heading"><Sparkles size={23}/><div><h2>AI & Codex</h2><span className={`integration-status ${statuses.ai}`}>{labels[statuses.ai]}</span></div></div>
        <p>Brain und Projektkontext nutzen, Texte vorbereiten und freigegebene CreatorOS-Aktionen ausführen.</p>
        {!data.integrations.ai.enabled && !aiOpen && <button className="button-secondary" onClick={() => { setAi(data.integrations.ai); setAiOpen(true); }}><Link size={17}/> AI verbinden</button>}
        {data.integrations.ai.enabled && <><div className="integration-summary"><b>OpenAI API · {data.integrations.ai.model}</b><span>{data.integrations.ai.mode === "auto" ? "Freigegebene Aktionen automatisch" : data.integrations.ai.mode === "confirm" ? "Vor Änderungen bestätigen" : "Nur Vorschläge"}</span><small>{data.integrations.ai.message}</small></div><div className="integration-actions"><button className="button-secondary" disabled={busy} onClick={() => void run("ai","test")}>Verbindung testen</button><button className="button-ghost" disabled={busy} onClick={() => { setAi(data.integrations.ai); setAiOpen(!aiOpen); }}><Settings2 size={17}/>{aiOpen ? "Schließen" : "Einstellungen / neu verbinden"}</button><button className="button-ghost" disabled={busy} onClick={() => setDisconnect("ai")}><Unplug size={17}/> Trennen</button></div></>}
        {aiOpen && <form className="integration-form" onSubmit={(event) => { event.preventDefault(); void run("ai","save",{ ...ai, apiKey: apiKey.current?.value || "" }); }}><p>Direkte Verbindung per OpenAI-API-Schlüssel. API-Nutzung wird separat abgerechnet. Ein ChatGPT-/Codex-Abo-Login ist in diesem Add-on noch nicht angebunden; es gibt keinen Device-Code-Flow.</p><label>API-Schlüssel<input ref={apiKey} type="password" autoComplete="off" placeholder={data.integrations.ai.secretId ? "Gespeichert · leer lassen zum Behalten" : "API-Schlüssel einfügen"}/></label><label>Modell-ID<input value={ai.model} onChange={(event) => setAi({ ...ai, model: event.target.value })} required placeholder="gpt-6-luna"/></label><fieldset><legend>Was darf die AI tun?</legend><p>Alle Freigaben sind anfangs aus. Ein nicht freigegebener Aufruf wird vom Server abgelehnt.</p><div className="permission-list">{(Object.entries(permissionLabels) as [AiPermission,string][]).map(([permission,label]) => <label key={permission}><input type="checkbox" checked={ai.permissions.includes(permission)} onChange={(event) => togglePermission(permission, event.target.checked)}/>{label}</label>)}</div><small>Mit Upload- und Zuordnungsfreigabe kann die AI TXT-/JSON-Dateien erzeugen und im gewählten Speicher ablegen. Binäre Dateien lädst du über Dateiauswahl / Drag & Drop hoch.</small></fieldset><label>Modus<select value={ai.mode} onChange={(event) => setAi({ ...ai, mode: event.target.value as typeof ai.mode })}><option value="suggest">Nur Vorschläge</option><option value="confirm">Vor Änderungen bestätigen</option><option value="auto">Erlaubte Aktionen automatisch ausführen</option></select></label><details className="integration-advanced"><summary>Zusätzliche Bestätigung im automatischen Modus</summary><div className="permission-list">{(Object.entries(permissionLabels) as [AiPermission,string][]).map(([permission,label]) => <label key={permission}><input type="checkbox" checked={ai.requireConfirmation.includes(permission)} onChange={(event) => toggleConfirmation(permission,event.target.checked)}/>{label}</label>)}</div></details><button className="button-primary" disabled={busy}>AI-Einstellungen speichern</button></form>}
      </article>
      <article className="integration-card"><div className="integration-heading"><HardDrive size={23}/><div><h2>NAS / Medienspeicher</h2><span className={`integration-status ${statuses.nas}`}>{labels[statuses.nas]}</span></div></div><p>Dateien verständlich nach Projekt und Dateityp ablegen. Ohne NAS nutzt CreatorOS seinen Datenordner.</p>
        {!data.integrations.nas.enabled && !nasOpen && <button className="button-secondary" onClick={() => { setNas(data.integrations.nas); setNasOpen(true); }}><Link size={17}/> NAS verbinden</button>}
        {data.integrations.nas.enabled && <><div className="integration-summary"><b>{data.integrations.nas.name || "NAS"}</b><span>{data.integrations.nas.host} · {data.integrations.nas.baseFolder}</span><small>{data.integrations.nas.message}</small></div><div className="integration-actions"><button className="button-secondary" disabled={busy} onClick={() => void run("nas","test")}>Verbindung testen</button><button className="button-ghost" disabled={busy} onClick={() => { setNas(data.integrations.nas); setNasOpen(!nasOpen); }}><Settings2 size={17}/>{nasOpen ? "Schließen" : "Einstellungen"}</button><button className="button-ghost" disabled={busy} onClick={() => setDisconnect("nas")}><Unplug size={17}/> Trennen</button></div></>}
        {nasOpen && <form className="integration-form" onSubmit={(event) => { event.preventDefault(); void run("nas","save",{ ...nas, password: password.current?.value || "" }); }}><p>WebDAV muss auf deiner NAS aktiviert sein. Ordner entstehen erst beim Hochladen. Der Verbindungstest prüft den gespeicherten Basisordner.</p><label>Anzeigename<input value={nas.name} maxLength={100} onChange={(event) => setNas({ ...nas, name: event.target.value })} placeholder="Meine NAS"/></label><div className="integration-form-row"><label>Host / IP<input value={nas.host} required placeholder="192.168.1.20" onChange={(event) => setNas({ ...nas, host: event.target.value })}/></label><label>Port<input type="number" min={1} max={65535} required value={nas.port} onChange={(event) => setNas({ ...nas, port: Number(event.target.value) })}/></label></div><label>Verbindung<select value={nas.protocol} onChange={(event) => setNas({ ...nas, protocol: event.target.value as typeof nas.protocol, port: event.target.value === "webdav-https" ? 5006 : 5005 })}><option value="webdav-https">WebDAV HTTPS</option><option value="webdav-http">WebDAV HTTP</option></select></label>{nas.protocol === "webdav-http" && <small>HTTP überträgt Zugangsdaten unverschlüsselt. Für die NAS-Verbindung wird HTTPS empfohlen.</small>}<label>Benutzername<input value={nas.username} required autoComplete="off" onChange={(event) => setNas({ ...nas, username: event.target.value })}/></label><label>Passwort<input ref={password} type="password" autoComplete="new-password" placeholder={data.integrations.nas.secretId ? "Gespeichert · leer lassen zum Behalten" : "NAS-Passwort"}/></label><label>Basisordner / WebDAV-Pfad<input value={nas.baseFolder} required onChange={(event) => setNas({ ...nas, baseFolder: event.target.value })} placeholder="/CreatorOS"/></label><button className="button-primary" disabled={busy}>NAS-Einstellungen speichern</button></form>}
      </article>
    </div>
    {disconnect && <div className="integration-disconnect" role="alertdialog" aria-labelledby="disconnect-title"><h2 id="disconnect-title">{disconnect === "ai" ? "AI-Verbindung" : "NAS-Verbindung"} trennen?</h2><p>Gespeicherte Zugangsdaten werden entfernt. {disconnect === "nas" ? "Dateien und Medienreferenzen bleiben erhalten. NAS-Dateien sind bis zum erneuten Verbinden nicht verfügbar." : "Manuelle Funktionen und dein Brain bleiben verfügbar."}</p><div className="screen-action-group"><button className="button-secondary" disabled={busy} onClick={() => setDisconnect(null)}>Abbrechen</button><button className="button-primary" disabled={busy} onClick={() => void run(disconnect,"disconnect")}>Verbindung trennen</button></div></div>}
  </section>;
}
