"use client";
import { useEffect, useState } from "react";
import { Check, ChevronDown, ChevronRight, File, Folder, FolderOpen, Pencil, Plus, RefreshCw } from "lucide-react";
import type { CreatorState, Project, Task } from "@/lib/model";
import { isoDateTime, localDateTime, manualAction } from "@/lib/client-api";
import { MediaPanel } from "@/components/media-panel";
import { EntityActions } from "@/components/entity-menu";
import { projectMediaRoot } from "@/lib/storage-paths";
import CompletionToggle from "@/components/completion-toggle";

export function TaskPanel({ data, project, onState }: { data: CreatorState; project: Project; onState: (state: CreatorState) => void }) {
  const [title, setTitle] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  return <section className="task-panel"><h2>Aufgaben</h2><p>Der markierte nächste Schritt erscheint auch auf Heute. Rechtsklick oder lange drücken zum Bearbeiten und Verwalten.</p><form className="task-create" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setError(""); try { await manualAction({ name: "createTask", args: { projectId: project.id, title } }, onState); setTitle(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Aufgabe konnte nicht erstellt werden."); } finally { setBusy(false); } }}><input aria-label="Neue Aufgabe" value={title} maxLength={200} required onChange={(event) => setTitle(event.target.value)} placeholder="Was ist konkret zu tun?"/><button className="button-primary" disabled={busy || !title.trim()}><Plus size={17}/> Aufgabe hinzufügen</button></form>{error && <p className="brain-error" role="alert">{error}</p>}<div className="task-list">{data.tasks.filter((task) => task.projectId === project.id).map((task) => <TaskCard key={task.id} task={task} data={data} onState={onState}/>)}</div></section>;
}
function TaskCard({ task, data, onState }: { task: Task; data: CreatorState; onState: (state: CreatorState) => void }) {
  const [open, setOpen] = useState(false); const [title, setTitle] = useState(task.title); const [description, setDescription] = useState(task.description); const [due, setDue] = useState(localDateTime(task.dueAt)); const [targetProject, setTargetProject] = useState(task.projectId); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const act = async (name: string, args: Record<string, unknown>) => {
    setBusy(true); setError(""); try { await manualAction({ name, args: { id: task.id, ...args } }, onState); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "Aufgabe konnte nicht geändert werden."); return false; } finally { setBusy(false); }
  };
  const priority = data.projects.find((project) => project.id === task.projectId)?.nextTaskId === task.id;
  return <EntityActions name={task.title} onRename={(title) => manualAction({ name: "updateTask",args: { id: task.id,title } },onState)} onDelete={() => manualAction({ name: "deleteTask",args: { id: task.id,confirm: true } },onState)} deleteDescription="Aufgabe und ihre Medienzuordnungen entfernen. Dateien bleiben in der Medienübersicht." actions={[{ label: "Bearbeiten / Anhänge",run: () => { setTitle(task.title); setDescription(task.description); setDue(localDateTime(task.dueAt)); setTargetProject(task.projectId); setOpen(true); } },...(task.status !== "done" && !priority ? [{ label: "Als nächsten Schritt wählen",run: () => manualAction({ name: "updateContent",args: { id: task.projectId,nextTaskId: task.id } },onState) }] : [])]}><article className={`task-card ${priority ? "task-is-next" : ""}`}><div className="task-card-top"><CompletionToggle checked={task.status === "done"} disabled={busy} label={task.status === "done" ? "Wieder öffnen" : "Abhaken"} onChange={() => void act(task.status === "done" ? "updateTask" : "completeTask",task.status === "done" ? { status: "open" } : {})}/><button className="task-title" onClick={() => { setOpen(!open); if (!open) { setTitle(task.title); setDescription(task.description); setDue(localDateTime(task.dueAt)); setTargetProject(task.projectId); } }}><b>{task.title}</b>{priority && <small className="next-task-label">Nächster Schritt</small>}{task.dueAt && <small>{new Date(task.dueAt).toLocaleString("de-AT")}</small>}<ChevronDown size={17}/></button><select aria-label="Aufgabenstatus" value={task.status} disabled={busy} onChange={(event) => void act("updateTask", { status: event.target.value })}><option value="open">Offen</option><option value="doing">In Arbeit</option><option value="done">Fertig</option></select></div>
    {error && <p className="brain-error" role="alert">{error}</p>}
    {open && <div className="task-details"><form className="integration-form" onSubmit={async (event) => { event.preventDefault(); await act("updateTask", { title, description, dueAt: isoDateTime(due), projectId: targetProject }); }}><label>Aufgabe<input value={title} maxLength={200} required onChange={(event) => setTitle(event.target.value)}/></label><label>Beschreibung<textarea rows={3} maxLength={2000} value={description} onChange={(event) => setDescription(event.target.value)}/></label><label>Termin (optional)<input type="datetime-local" value={due} onChange={(event) => setDue(event.target.value)}/></label><label>Projekt<select value={targetProject} disabled={busy} onChange={(event) => setTargetProject(event.target.value)}>{data.projects.map((project) => <option key={project.id} value={project.id}>{project.title}</option>)}</select></label><button className="button-secondary" disabled={busy}>Änderungen speichern</button></form><h3>Anhänge & Referenzen</h3><MediaPanel data={data} entityType="task" entityId={task.id} onState={onState}/></div>}
  </article></EntityActions>;
}

export function ContentEditor({ project, onState }: { project: Project; onState: (state: CreatorState) => void }) {
  const [title, setTitle] = useState(project.title); const [summary, setSummary] = useState(project.summary); const [caption, setCaption] = useState(project.caption || ""); const [hooks, setHooks] = useState((project.hooks || []).join("\n")); const [platform, setPlatform] = useState(project.platform || "Other"); const [publish, setPublish] = useState(localDateTime(project.publishAt)); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  return <section className="content-editor"><h2>Upload Infos</h2><p>Titel, Beschreibung und Plattformdaten für deinen späteren Upload vorbereiten. Veröffentlicht wird weiterhin manuell.</p><form className="integration-form" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setMessage(""); try { await manualAction({ name: "updateContent", args: { id: project.id, title, summary, caption, hooks: hooks.split("\n").filter((line) => line.trim()), platform, publishAt: isoDateTime(publish) } }, onState); setMessage("Content gespeichert."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Content konnte nicht gespeichert werden."); } finally { setBusy(false); } }}>
    <label>Titel<input value={title} maxLength={100} required onChange={(event) => setTitle(event.target.value)}/></label><label>Beschreibung<textarea value={summary} maxLength={500} rows={3} onChange={(event) => setSummary(event.target.value)}/></label><label>Caption<textarea value={caption} maxLength={4000} rows={4} onChange={(event) => setCaption(event.target.value)}/></label><label>Hooks (ein Hook je Zeile)<textarea value={hooks} rows={3} onChange={(event) => setHooks(event.target.value)}/></label><div className="integration-form-row"><label>Plattform<select value={platform} onChange={(event) => setPlatform(event.target.value as typeof platform)}>{["Instagram","TikTok","YouTube","Other"].map((name) => <option key={name}>{name}</option>)}</select></label><label>Geplante Veröffentlichung<input type="datetime-local" value={publish} onChange={(event) => setPublish(event.target.value)}/></label></div><button className="button-primary" disabled={busy}>Content speichern</button>{message && <p role="status">{message}</p>}
  </form></section>;
}

type ProjectEntry = { name: string; directory: boolean; size: number };
export function ProjectFileBrowser({ data, project, onState }: { data: CreatorState; project: Project; onState: (state: CreatorState) => void }) {
  const [folder, setFolder] = useState(""); const [entries, setEntries] = useState<ProjectEntry[]>([]); const [explorerPath, setExplorerPath] = useState("");
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [dropTarget, setDropTarget] = useState("");
  const [dialog, setDialog] = useState<{ action: "mkdir" | "rename"; path?: string; name: string } | null>(null);
  const smb = data.integrations.nas.enabled && data.integrations.nas.protocol === "smb";
  const root = projectMediaRoot(project);
  const load = async (nextFolder = folder) => {
    if (!smb) return;
    setBusy(true); setError("");
    try {
      const params = new URLSearchParams({ projectId: project.id, path: nextFolder ? root + "/" + nextFolder : "" });
      const response = await fetch("/api/project-files?" + params, { cache: "no-store" }); const payload = await response.json();
      if (!response.ok) throw new Error(payload.error || "Projektordner konnte nicht gelesen werden.");
      setEntries(payload.entries || []); setExplorerPath(payload.explorerPath || "");
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Projektordner konnte nicht gelesen werden."); }
    finally { setBusy(false); }
  };
  useEffect(() => { setFolder(""); void load(""); }, [project.id, smb]);
  const currentPath = folder ? root + "/" + folder : root;
  const post = async (body: Record<string, unknown>) => {
    setBusy(true); setError(""); setMessage("");
    try {
      const response = await fetch("/api/project-files", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId: project.id, ...body }) }); const payload = await response.json();
      if (!response.ok) throw new Error(payload.error || "Ordneraktion fehlgeschlagen.");
      if (payload.state) onState(payload.state);
      await load(); setMessage(body.action === "ensureProjectFolder" ? payload.created ? "Projektordner wurde angelegt. Vorhandene Inhalte bleiben erhalten." : "Projektordner ist bereits vorhanden. Nichts wurde verändert." : body.action === "mkdir" ? "Ordner erstellt." : body.action === "rename" ? "Ordner umbenannt." : "Element verschoben.");
      return true;
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Ordneraktion fehlgeschlagen."); return false; }
    finally { setBusy(false); }
  };
  const move = async (source: string, destination: string) => {
    if (source === destination || destination.startsWith(source + "/")) return;
    await post({ action: "move", from: source, to: destination ? root + "/" + destination : root });
  };
  const crumbs = folder ? folder.split("/") : [];
  const formatSize = (size: number) => size >= 1024 * 1024 ? (size / 1024 / 1024).toFixed(1) + " MB" : Math.max(1, Math.ceil(size / 1024)) + " KB";
  const navigate = (path: string) => { setFolder(path); void load(path); };
  return <section className="project-file-browser">
    <header className="project-browser-header"><div><span className="action-label">PROJEKTMATERIAL</span><h2>Dateien & Ordner</h2><p>Auch Ordner aus dem Explorer werden hier angezeigt.</p></div><div className="project-browser-actions"><button className="button-secondary" disabled={!smb || busy} title="Prüft den Projektordner und legt ihn nur an, wenn er fehlt. Vorhandene Inhalte werden nicht gelöscht." onClick={() => void post({ action: "ensureProjectFolder" })}><FolderOpen size={17}/> Projektordner prüfen / anlegen</button><button className="button-secondary" disabled={!smb || busy} onClick={() => { setMessage(""); setDialog({ action: "mkdir", name: "" }); }}><Plus size={17}/> Neuer Ordner</button></div></header>
    {!smb ? <div className="project-browser-empty"><FolderOpen size={23}/><b>SMB-Dateibrowser nicht verbunden</b><span>Verbinde zuerst deine SMB-Freigabe unter Einstellungen → Integrationen.</span></div> : <>
      <div className="project-browser-location"><div className="project-browser-crumbs" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); setDropTarget(""); const source = event.dataTransfer.getData("text/plain"); if (source) void move(source, ""); }}><button onClick={() => navigate("")}>Projektordner</button>{crumbs.map((part, index) => { const path = crumbs.slice(0,index + 1).join("/"); return <span key={path}><ChevronRight size={14}/><button onClick={() => navigate(path)}>{part}</button></span>; })}</div><button className="button-ghost explorer-copy" title="Explorer-Pfad kopieren" onClick={() => void navigator.clipboard.writeText(explorerPath).then(() => setMessage("Explorer-Pfad kopiert.")).catch(() => setError("Explorer-Pfad konnte nicht kopiert werden."))}>Explorer-Pfad kopieren</button></div>
      {error && <p className="brain-error" role="alert">{error}</p>}{message && <p className="project-browser-message" role="status">{message}</p>}
      <div className="project-browser-list" aria-busy={busy}>
        <div className="project-browser-list-head"><span>Name</span><span>Typ / Größe</span><span>Aktion</span></div>
        {folder && <button className="project-browser-parent" onClick={() => navigate(crumbs.slice(0,-1).join("/"))}><FolderOpen size={18}/> Übergeordneter Ordner</button>}
        {entries.slice().sort((a,b) => Number(b.directory)-Number(a.directory) || a.name.localeCompare(b.name,"de")).map((entry) => {
          const itemPath = currentPath + "/" + entry.name; const target = folder ? folder + "/" + entry.name : entry.name;
          return <div key={itemPath} className={"project-browser-row " + (dropTarget === itemPath ? "is-drop-target" : "")} draggable onDragStart={(event) => { event.dataTransfer.setData("text/plain",itemPath); event.dataTransfer.effectAllowed = "move"; }} onDragOver={(event) => { if (entry.directory) { event.preventDefault(); setDropTarget(itemPath); } }} onDragLeave={() => setDropTarget("")} onDrop={(event) => { if (!entry.directory) return; event.preventDefault(); event.stopPropagation(); setDropTarget(""); const source = event.dataTransfer.getData("text/plain"); if (source) void move(source,target); }}>
            <button className="project-browser-entry-name" onClick={() => entry.directory && navigate(target)} disabled={!entry.directory || busy}>{entry.directory ? <Folder size={19}/> : <File size={18}/>}<span>{entry.name}</span>{entry.directory && <ChevronRight size={15}/>}</button><span className="project-browser-meta">{entry.directory ? "Ordner" : formatSize(entry.size)}</span>{entry.directory ? <button className="project-browser-rename" aria-label={entry.name + " umbenennen"} title="Ordner umbenennen" disabled={busy} onClick={() => setDialog({ action: "rename", path: itemPath, name: entry.name })}><Pencil size={16}/></button> : <span/>}
          </div>;
        })}
        {!entries.length && !busy && <div className="project-browser-empty"><FolderOpen size={22}/><b>Dieser Ordner ist noch leer.</b><span>Lege einen Ordner an oder lade Dateien im seitlichen Medienbereich hoch.</span></div>}
        {busy && <p className="project-browser-loading"><RefreshCw size={16}/> Wird geladen …</p>}
      </div><p className="project-browser-hint">Dateien oder Ordner auf einen Zielordner ziehen, um sie zu verschieben.</p>
    </>}
    {dialog && <div className="modal-backdrop"><form className="dialog" role="dialog" aria-modal="true" aria-label={dialog.action === "mkdir" ? "Ordner erstellen" : "Ordner umbenennen"} onSubmit={(event) => { event.preventDefault(); const name = dialog.name.trim(); if (!name) return; const action = dialog.action === "mkdir" ? { action: "mkdir", path: folder ? root + "/" + folder : root, name } : { action: "rename", from: dialog.path, name }; void post(action).then((saved) => { if (saved) setDialog(null); }); }}><h2>{dialog.action === "mkdir" ? "Neuen Ordner erstellen" : "Ordner umbenennen"}</h2><label>Ordnername<input autoFocus value={dialog.name} maxLength={90} required onChange={(event) => setDialog({ ...dialog, name: event.target.value })}/></label>{error && <p className="brain-error" role="alert">{error}</p>}<div className="screen-action-group"><button type="button" className="button-secondary" disabled={busy} onClick={() => setDialog(null)}>Abbrechen</button><button className="button-primary" disabled={busy || !dialog.name.trim()}>{busy ? "Wird gespeichert …" : dialog.action === "mkdir" ? "Erstellen" : "Speichern"}</button></div></form></div>}
  </section>;
}

export function PlanningScreen({ data, onState }: { data: CreatorState; onState: (state: CreatorState) => void }) {
  const [title, setTitle] = useState(""); const [startsAt, setStartsAt] = useState(""); const [projectId, setProjectId] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  return <section><div className="screen-heading"><div><div className="eyebrow">VORBEREITEN</div><h1>Planung</h1><p>Termine und geplante Veröffentlichungen an einem Ort.</p></div></div><form className="integration-form planning-create" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setMessage(""); try { await manualAction({ name: "createPlanning", args: { title, startsAt: isoDateTime(startsAt), projectId: projectId || null } }, onState); setTitle(""); setStartsAt(""); setMessage("Planung gespeichert."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Planung konnte nicht gespeichert werden."); } finally { setBusy(false); } }}><label>Planung<input value={title} required maxLength={200} onChange={(event) => setTitle(event.target.value)}/></label><div className="integration-form-row"><label>Wann?<input type="datetime-local" value={startsAt} required onChange={(event) => setStartsAt(event.target.value)}/></label><label>Projekt (optional)<select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Ohne Zuordnung</option>{data.projects.map((project) => <option key={project.id} value={project.id}>{project.title}</option>)}</select></label></div><button className="button-primary" disabled={busy || !startsAt}>Planung hinzufügen</button>{message && <p role="status">{message}</p>}</form><div className="planning-list">
    {[...data.planning].sort((a,b) => a.startsAt.localeCompare(b.startsAt)).map((entry) => <PlanningCard key={entry.id} entry={entry} onState={onState}/>)}
    {data.projects.filter((project) => project.publishAt).sort((a,b) => a.publishAt!.localeCompare(b.publishAt!)).map((project) => <article className="planning-card" key={project.id}><b>{project.title}</b><span>{new Date(project.publishAt!).toLocaleString("de-AT")} · {project.platform || "Other"} · Veröffentlichung</span></article>)}
    {data.tasks.filter((task) => task.dueAt && task.status !== "done").sort((a,b) => a.dueAt!.localeCompare(b.dueAt!)).map((task) => <article className="planning-card" key={task.id}><b>{task.title}</b><span>{new Date(task.dueAt!).toLocaleString("de-AT")} · Aufgabe</span></article>)}
  </div></section>;
}
function PlanningCard({ entry, onState }: { entry: CreatorState["planning"][number]; onState: (state: CreatorState) => void }) {
  const [editing, setEditing] = useState(false); const [title, setTitle] = useState(entry.title); const [date, setDate] = useState(localDateTime(entry.startsAt)); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  return <EntityActions name={entry.title} onRename={(title) => manualAction({ name: "updatePlanning",args: { id: entry.id,title } },onState)} onDelete={() => manualAction({ name: "deletePlanning",args: { id: entry.id,confirm: true } },onState)} actions={[{ label: "Termin bearbeiten",run: () => { setTitle(entry.title); setDate(localDateTime(entry.startsAt)); setEditing(true); } }]}><article className="planning-card">{editing ? <form className="integration-form" onSubmit={async (event) => { event.preventDefault(); setBusy(true); try { await manualAction({ name: "updatePlanning", args: { id: entry.id, title, startsAt: isoDateTime(date) } }, onState); setEditing(false); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Änderung fehlgeschlagen."); } finally { setBusy(false); } }}><label>Titel<input value={title} required onChange={(event) => setTitle(event.target.value)}/></label><label>Wann?<input type="datetime-local" value={date} required onChange={(event) => setDate(event.target.value)}/></label><div className="screen-action-group"><button className="button-primary" disabled={busy}>Speichern</button><button type="button" className="button-ghost" disabled={busy} onClick={() => setEditing(false)}>Abbrechen</button></div>{message && <p role="alert">{message}</p>}</form> : <><b>{entry.title}</b><span>{new Date(entry.startsAt).toLocaleString("de-AT")}</span></>}</article></EntityActions>;
}
