"use client";
import { useState } from "react";
import { Check, ChevronDown, Plus } from "lucide-react";
import type { CreatorState, Project, Task } from "@/lib/model";
import { isoDateTime, localDateTime, manualAction } from "@/lib/client-api";
import { MediaPanel } from "@/components/media-panel";

export function TaskPanel({ data, project, onState }: { data: CreatorState; project: Project; onState: (state: CreatorState) => void }) {
  const [title, setTitle] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  return <section className="task-panel"><h2>Aufgaben</h2><p>Einzelne Arbeitsschritte für dieses Projekt.</p><form className="task-create" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setError(""); try { await manualAction({ name: "createTask", args: { projectId: project.id, title } }, onState); setTitle(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Aufgabe konnte nicht erstellt werden."); } finally { setBusy(false); } }}><input aria-label="Neue Aufgabe" value={title} maxLength={200} required onChange={(event) => setTitle(event.target.value)} placeholder="Was ist konkret zu tun?"/><button className="button-primary" disabled={busy || !title.trim()}><Plus size={17}/> Aufgabe hinzufügen</button></form>{error && <p className="brain-error" role="alert">{error}</p>}<div className="task-list">{data.tasks.filter((task) => task.projectId === project.id).map((task) => <TaskCard key={task.id} task={task} data={data} onState={onState}/>)}</div></section>;
}
function TaskCard({ task, data, onState }: { task: Task; data: CreatorState; onState: (state: CreatorState) => void }) {
  const [open, setOpen] = useState(false); const [title, setTitle] = useState(task.title); const [description, setDescription] = useState(task.description); const [due, setDue] = useState(localDateTime(task.dueAt)); const [targetProject, setTargetProject] = useState(task.projectId); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const act = async (name: string, args: Record<string, unknown>) => {
    setBusy(true); setError(""); try { await manualAction({ name, args: { id: task.id, ...args } }, onState); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "Aufgabe konnte nicht geändert werden."); return false; } finally { setBusy(false); }
  };
  return <article className="task-card"><div className="task-card-top"><button className="icon-quiet" disabled={busy} aria-label={task.status === "done" ? "Aufgabe wieder öffnen" : "Aufgabe abschließen"} onClick={() => void act(task.status === "done" ? "updateTask" : "completeTask", task.status === "done" ? { status: "open" } : {})}><Check size={20} className={task.status === "done" ? "task-done" : ""}/></button><button className="task-title" onClick={() => { setOpen(!open); if (!open) { setTitle(task.title); setDescription(task.description); setDue(localDateTime(task.dueAt)); setTargetProject(task.projectId); } }}><b>{task.title}</b>{task.dueAt && <small>{new Date(task.dueAt).toLocaleString("de-AT")}</small>}<ChevronDown size={17}/></button><select aria-label="Aufgabenstatus" value={task.status} disabled={busy} onChange={(event) => void act("updateTask", { status: event.target.value })}><option value="open">Offen</option><option value="doing">In Arbeit</option><option value="done">Fertig</option></select></div>
    {error && <p className="brain-error" role="alert">{error}</p>}
    {open && <div className="task-details"><form className="integration-form" onSubmit={async (event) => { event.preventDefault(); await act("updateTask", { title, description, dueAt: isoDateTime(due), projectId: targetProject }); }}><label>Aufgabe<input value={title} maxLength={200} required onChange={(event) => setTitle(event.target.value)}/></label><label>Beschreibung<textarea rows={3} maxLength={2000} value={description} onChange={(event) => setDescription(event.target.value)}/></label><label>Termin (optional)<input type="datetime-local" value={due} onChange={(event) => setDue(event.target.value)}/></label><label>Projekt<select value={targetProject} disabled={busy} onChange={(event) => setTargetProject(event.target.value)}>{data.projects.map((project) => <option key={project.id} value={project.id}>{project.title}</option>)}</select></label><button className="button-secondary" disabled={busy}>Änderungen speichern</button></form><h3>Anhänge & Referenzen</h3><MediaPanel data={data} entityType="task" entityId={task.id} onState={onState}/></div>}
  </article>;
}

export function ContentEditor({ project, onState }: { project: Project; onState: (state: CreatorState) => void }) {
  const [title, setTitle] = useState(project.title); const [summary, setSummary] = useState(project.summary); const [caption, setCaption] = useState(project.caption || ""); const [hooks, setHooks] = useState((project.hooks || []).join("\n")); const [platform, setPlatform] = useState(project.platform || "Other"); const [publish, setPublish] = useState(localDateTime(project.publishAt)); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  return <section className="content-editor"><h2>Content & Veröffentlichung</h2><p>Texte vorbereiten und einen Veröffentlichungstermin vormerken. Die Veröffentlichung selbst bleibt manuell.</p><form className="integration-form" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setMessage(""); try { await manualAction({ name: "updateContent", args: { id: project.id, title, summary, caption, hooks: hooks.split("\n").filter((line) => line.trim()), platform, publishAt: isoDateTime(publish) } }, onState); setMessage("Content gespeichert."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Content konnte nicht gespeichert werden."); } finally { setBusy(false); } }}>
    <label>Titel<input value={title} maxLength={100} required onChange={(event) => setTitle(event.target.value)}/></label><label>Beschreibung<textarea value={summary} maxLength={500} rows={3} onChange={(event) => setSummary(event.target.value)}/></label><label>Caption<textarea value={caption} maxLength={4000} rows={4} onChange={(event) => setCaption(event.target.value)}/></label><label>Hooks (ein Hook je Zeile)<textarea value={hooks} rows={3} onChange={(event) => setHooks(event.target.value)}/></label><div className="integration-form-row"><label>Plattform<select value={platform} onChange={(event) => setPlatform(event.target.value as typeof platform)}>{["Instagram","TikTok","YouTube","Other"].map((name) => <option key={name}>{name}</option>)}</select></label><label>Geplante Veröffentlichung<input type="datetime-local" value={publish} onChange={(event) => setPublish(event.target.value)}/></label></div><button className="button-primary" disabled={busy}>Content speichern</button>{message && <p role="status">{message}</p>}
  </form></section>;
}

export function PlanningScreen({ data, onState }: { data: CreatorState; onState: (state: CreatorState) => void }) {
  const [title, setTitle] = useState(""); const [startsAt, setStartsAt] = useState(""); const [projectId, setProjectId] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  return <section><div className="screen-heading"><div><div className="eyebrow">VORBEREITEN</div><h1>Planung</h1><p>Termine und geplante Veröffentlichungen an einem Ort.</p></div></div><form className="integration-form planning-create" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setMessage(""); try { await manualAction({ name: "createPlanning", args: { title, startsAt: isoDateTime(startsAt), projectId: projectId || null } }, onState); setTitle(""); setStartsAt(""); setMessage("Planung gespeichert."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Planung konnte nicht gespeichert werden."); } finally { setBusy(false); } }}><label>Planung<input value={title} required maxLength={200} onChange={(event) => setTitle(event.target.value)}/></label><div className="integration-form-row"><label>Wann?<input type="datetime-local" value={startsAt} required onChange={(event) => setStartsAt(event.target.value)}/></label><label>Projekt (optional)<select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Ohne Zuordnung</option>{data.projects.map((project) => <option key={project.id} value={project.id}>{project.title}</option>)}</select></label></div><button className="button-primary" disabled={busy || !startsAt}>Planung hinzufügen</button>{message && <p role="status">{message}</p>}</form><div className="planning-list">
    {[...data.planning].sort((a,b) => a.startsAt.localeCompare(b.startsAt)).map((entry) => <PlanningCard key={entry.id} entry={entry} onState={onState}/>)}
    {data.projects.filter((project) => project.publishAt).sort((a,b) => a.publishAt!.localeCompare(b.publishAt!)).map((project) => <article className="planning-card" key={project.id}><b>{project.title}</b><span>{new Date(project.publishAt!).toLocaleString("de-AT")} · {project.platform || "Other"} · Veröffentlichung</span></article>)}
    {data.tasks.filter((task) => task.dueAt && task.status !== "done").sort((a,b) => a.dueAt!.localeCompare(b.dueAt!)).map((task) => <article className="planning-card" key={task.id}><b>{task.title}</b><span>{new Date(task.dueAt!).toLocaleString("de-AT")} · Aufgabe</span></article>)}
  </div></section>;
}
function PlanningCard({ entry, onState }: { entry: CreatorState["planning"][number]; onState: (state: CreatorState) => void }) {
  const [editing, setEditing] = useState(false); const [title, setTitle] = useState(entry.title); const [date, setDate] = useState(localDateTime(entry.startsAt)); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  return <article className="planning-card">{editing ? <form className="integration-form" onSubmit={async (event) => { event.preventDefault(); setBusy(true); try { await manualAction({ name: "updatePlanning", args: { id: entry.id, title, startsAt: isoDateTime(date) } }, onState); setEditing(false); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Änderung fehlgeschlagen."); } finally { setBusy(false); } }}><label>Titel<input value={title} required onChange={(event) => setTitle(event.target.value)}/></label><label>Wann?<input type="datetime-local" value={date} required onChange={(event) => setDate(event.target.value)}/></label><div className="screen-action-group"><button className="button-primary" disabled={busy}>Speichern</button><button type="button" className="button-ghost" disabled={busy} onClick={() => setEditing(false)}>Abbrechen</button></div>{message && <p role="alert">{message}</p>}</form> : <><b>{entry.title}</b><span>{new Date(entry.startsAt).toLocaleString("de-AT")}</span><button className="button-ghost" onClick={() => { setTitle(entry.title); setDate(localDateTime(entry.startsAt)); setEditing(true); }}>Bearbeiten</button></>}</article>;
}
